[config]
default_to_workspace = false

[tasks.default]
clear = true
script_runner = "@duckscript"
script = '''
cm_run_task clean
cm_run_task build
cm_run_task multicall-default-utils
cm_run_task multicall-specific-utils
'''

[tasks.build]
clear = true
command = "cargo"
args = ["build", "--release"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.multicall-default-utils]
condition = { env_not_set = [" MULTICALL_UTILS" ] }
cwd = "./src/eu_multicall/"
command = "cargo"
args = ["build", "--release"]

[tasks.multicall-specific-utils]
condition = { env_set = [ "MULTICALL_UTILS" ] }
cwd = "./src/eu_multicall/"
command = "cargo"
args = [
    "build",
    "--release",
    "--no-default-features", 
    "--features",
    "${MULTICALL_UTILS}"
]

[tasks.one]
command = "cargo"
args = [
    "run",
    "-p",
    "${@}"
]